[package]
name = "minikin-rs"
version = "0.1.0"
authors = ["Pavel Sergeev <pavel.sergeev@jetbrains.com>"]
edition = "2018"
build = "build.rs"


[build-dependencies.cmake]
version = "0.1"

[dependencies]
libc = "0.2"
